// ============ Verbs Data with Examples ============
export const datasets = {
    verbs: [
        { infinitive: 'be', translation: 'быть', pastSimple: 'was/were', pastParticiple: 'been', example: 'I <strong>was</strong> at home yesterday.' },
        { infinitive: 'beat', translation: 'бить', pastSimple: 'beat', pastParticiple: 'beaten', example: 'Our team <strong>beat</strong> them 3-0.' },
        { infinitive: 'become', translation: 'становиться', pastSimple: 'became', pastParticiple: 'become', example: 'She <strong>became</strong> a doctor.' },
        { infinitive: 'begin', translation: 'начинать', pastSimple: 'began', pastParticiple: 'begun', example: 'The movie <strong>began</strong> at 8 PM.' },
        { infinitive: 'bite', translation: 'кусать', pastSimple: 'bit', pastParticiple: 'bitten', example: 'The dog <strong>bit</strong> me!' },
        { infinitive: 'blow', translation: 'дуть', pastSimple: 'blew', pastParticiple: 'blown', example: 'The wind <strong>blew</strong> hard.' },
        { infinitive: 'break', translation: 'ломать(ся)', pastSimple: 'broke', pastParticiple: 'broken', example: 'He <strong>broke</strong> the window.' },
        { infinitive: 'bring', translation: 'приносить', pastSimple: 'brought', pastParticiple: 'brought', example: 'She <strong>brought</strong> me flowers.' },
        { infinitive: 'build', translation: 'строить', pastSimple: 'built', pastParticiple: 'built', example: 'They <strong>built</strong> a new house.' },
        { infinitive: 'burst', translation: 'разрывать(ся)', pastSimple: 'burst', pastParticiple: 'burst', example: 'The balloon <strong>burst</strong> suddenly.' },
        { infinitive: 'buy', translation: 'покупать', pastSimple: 'bought', pastParticiple: 'bought', example: 'I <strong>bought</strong> a new car.' },
        { infinitive: 'catch', translation: 'ловить', pastSimple: 'caught', pastParticiple: 'caught', example: 'He <strong>caught</strong> the ball.' },
        { infinitive: 'choose', translation: 'выбирать', pastSimple: 'chose', pastParticiple: 'chosen', example: 'She <strong>chose</strong> the red dress.' },
        { infinitive: 'come', translation: 'приходить', pastSimple: 'came', pastParticiple: 'come', example: 'He <strong>came</strong> home late.' },
        { infinitive: 'cost', translation: 'стоить', pastSimple: 'cost', pastParticiple: 'cost', example: 'It <strong>cost</strong> $100.' },
        { infinitive: 'deal', translation: 'раздавать', pastSimple: 'dealt', pastParticiple: 'dealt', example: 'He <strong>dealt</strong> the cards.' },
        { infinitive: 'dig', translation: 'копать(ся)', pastSimple: 'dug', pastParticiple: 'dug', example: 'The dog <strong>dug</strong> a hole.' },
        { infinitive: 'do', translation: 'делать', pastSimple: 'did', pastParticiple: 'done', example: 'I <strong>did</strong> my homework.' },
        { infinitive: 'draw', translation: 'рисовать', pastSimple: 'drew', pastParticiple: 'drawn', example: 'She <strong>drew</strong> a beautiful picture.' },
        { infinitive: 'drink', translation: 'пить', pastSimple: 'drank', pastParticiple: 'drunk', example: 'He <strong>drank</strong> coffee.' },
        { infinitive: 'drive', translation: 'ехать', pastSimple: 'drove', pastParticiple: 'driven', example: 'She <strong>drove</strong> to work.' },
        { infinitive: 'eat', translation: 'есть', pastSimple: 'ate', pastParticiple: 'eaten', example: 'We <strong>ate</strong> pizza.' },
        { infinitive: 'fall', translation: 'падать', pastSimple: 'fell', pastParticiple: 'fallen', example: 'He <strong>fell</strong> down.' },
        { infinitive: 'feed', translation: 'кормить', pastSimple: 'fed', pastParticiple: 'fed', example: 'She <strong>fed</strong> the cat.' },
        { infinitive: 'feel', translation: 'ощущать', pastSimple: 'felt', pastParticiple: 'felt', example: 'I <strong>felt</strong> happy.' },
        { infinitive: 'fight', translation: 'драться', pastSimple: 'fought', pastParticiple: 'fought', example: 'They <strong>fought</strong> bravely.' },
        { infinitive: 'find', translation: 'находить', pastSimple: 'found', pastParticiple: 'found', example: 'I <strong>found</strong> my keys.' },
        { infinitive: 'fly', translation: 'летать', pastSimple: 'flew', pastParticiple: 'flown', example: 'The bird <strong>flew</strong> away.' },
        { infinitive: 'forget', translation: 'забывать', pastSimple: 'forgot', pastParticiple: 'forgotten', example: 'I <strong>forgot</strong> her name.' },
        { infinitive: 'freeze', translation: 'замораживать', pastSimple: 'froze', pastParticiple: 'frozen', example: 'The lake <strong>froze</strong> in winter.' },
        { infinitive: 'get', translation: 'получать', pastSimple: 'got', pastParticiple: 'got/gotten', example: 'I <strong>got</strong> a gift.' },
        { infinitive: 'give', translation: 'давать', pastSimple: 'gave', pastParticiple: 'given', example: 'She <strong>gave</strong> me advice.' },
        { infinitive: 'go', translation: 'идти', pastSimple: 'went', pastParticiple: 'gone', example: 'He <strong>went</strong> to school.' },
        { infinitive: 'grow', translation: 'расти', pastSimple: 'grew', pastParticiple: 'grown', example: 'The tree <strong>grew</strong> tall.' },
        { infinitive: 'hang', translation: 'висеть', pastSimple: 'hung/hanged', pastParticiple: 'hung/hanged', example: 'She <strong>hung</strong> the picture.' },
        { infinitive: 'have', translation: 'иметь', pastSimple: 'had', pastParticiple: 'had', example: 'I <strong>had</strong> breakfast.' },
        { infinitive: 'hear', translation: 'слышать', pastSimple: 'heard', pastParticiple: 'heard', example: 'I <strong>heard</strong> the news.' },
        { infinitive: 'hide', translation: 'прятать(ся)', pastSimple: 'hid', pastParticiple: 'hidden', example: 'The cat <strong>hid</strong> under the bed.' },
        { infinitive: 'hit', translation: 'ударять', pastSimple: 'hit', pastParticiple: 'hit', example: 'He <strong>hit</strong> the ball.' },
        { infinitive: 'hold', translation: 'держать', pastSimple: 'held', pastParticiple: 'held', example: 'She <strong>held</strong> my hand.' },
        { infinitive: 'keep', translation: 'хранить', pastSimple: 'kept', pastParticiple: 'kept', example: 'I <strong>kept</strong> the secret.' },
        { infinitive: 'know', translation: 'знать', pastSimple: 'knew', pastParticiple: 'known', example: 'I <strong>knew</strong> the answer.' },
        { infinitive: 'lay', translation: 'класть', pastSimple: 'laid', pastParticiple: 'laid', example: 'She <strong>laid</strong> the book on the table.' },
        { infinitive: 'lead', translation: 'вести', pastSimple: 'led', pastParticiple: 'led', example: 'He <strong>led</strong> the team.' },
        { infinitive: 'learn', translation: 'учиться', pastSimple: 'learnt/learned', pastParticiple: 'learnt/learned', example: 'I <strong>learned</strong> English.' },
        { infinitive: 'leave', translation: 'уходить', pastSimple: 'left', pastParticiple: 'left', example: 'She <strong>left</strong> early.' },
        { infinitive: 'lend', translation: 'одалживать', pastSimple: 'lent', pastParticiple: 'lent', example: 'He <strong>lent</strong> me money.' },
        { infinitive: 'let', translation: 'разрешать', pastSimple: 'let', pastParticiple: 'let', example: 'They <strong>let</strong> me go.' },
        { infinitive: 'lie', translation: 'лежать', pastSimple: 'lay', pastParticiple: 'lain', example: 'He <strong>lay</strong> on the sofa.' },
        { infinitive: 'lose', translation: 'терять', pastSimple: 'lost', pastParticiple: 'lost', example: 'I <strong>lost</strong> my phone.' },
        { infinitive: 'make', translation: 'делать', pastSimple: 'made', pastParticiple: 'made', example: 'She <strong>made</strong> a cake.' },
        { infinitive: 'mean', translation: 'означать', pastSimple: 'meant', pastParticiple: 'meant', example: 'I <strong>meant</strong> to help.' },
        { infinitive: 'meet', translation: 'встречать', pastSimple: 'met', pastParticiple: 'met', example: 'We <strong>met</strong> at the cafe.' },
        { infinitive: 'pay', translation: 'платить', pastSimple: 'paid', pastParticiple: 'paid', example: 'I <strong>paid</strong> the bill.' },
        { infinitive: 'put', translation: 'класть', pastSimple: 'put', pastParticiple: 'put', example: 'He <strong>put</strong> the book down.' },
        { infinitive: 'read', translation: 'читать', pastSimple: 'read', pastParticiple: 'read', example: 'She <strong>read</strong> a novel.' },
        { infinitive: 'ride', translation: 'ехать верхом', pastSimple: 'rode', pastParticiple: 'ridden', example: 'He <strong>rode</strong> a horse.' },
        { infinitive: 'ring', translation: 'звенеть', pastSimple: 'rang', pastParticiple: 'rung', example: 'The phone <strong>rang</strong>.' },
        { infinitive: 'run', translation: 'бежать', pastSimple: 'ran', pastParticiple: 'run', example: 'She <strong>ran</strong> fast.' },
        { infinitive: 'say', translation: 'сказать', pastSimple: 'said', pastParticiple: 'said', example: 'He <strong>said</strong> hello.' },
        { infinitive: 'see', translation: 'видеть', pastSimple: 'saw', pastParticiple: 'seen', example: 'I <strong>saw</strong> a bird.' },
        { infinitive: 'seek', translation: 'искать', pastSimple: 'sought', pastParticiple: 'sought', example: 'She <strong>sought</strong> help.' },
        { infinitive: 'sell', translation: 'продавать', pastSimple: 'sold', pastParticiple: 'sold', example: 'He <strong>sold</strong> his car.' },
        { infinitive: 'send', translation: 'посылать', pastSimple: 'sent', pastParticiple: 'sent', example: 'I <strong>sent</strong> an email.' },
        { infinitive: 'set', translation: 'устанавливать', pastSimple: 'set', pastParticiple: 'set', example: 'She <strong>set</strong> the table.' },
        { infinitive: 'shake', translation: 'трясти', pastSimple: 'shook', pastParticiple: 'shaken', example: 'He <strong>shook</strong> hands.' },
        { infinitive: 'shine', translation: 'светить', pastSimple: 'shone', pastParticiple: 'shone', example: 'The sun <strong>shone</strong> brightly.' },
        { infinitive: 'shoot', translation: 'стрелять', pastSimple: 'shot', pastParticiple: 'shot', example: 'He <strong>shot</strong> the target.' },
        { infinitive: 'show', translation: 'показывать', pastSimple: 'showed', pastParticiple: 'shown', example: 'She <strong>showed</strong> me photos.' },
        { infinitive: 'shut', translation: 'закрывать', pastSimple: 'shut', pastParticiple: 'shut', example: 'He <strong>shut</strong> the door.' },
        { infinitive: 'sing', translation: 'петь', pastSimple: 'sang', pastParticiple: 'sung', example: 'She <strong>sang</strong> beautifully.' },
        { infinitive: 'sit', translation: 'сидеть', pastSimple: 'sat', pastParticiple: 'sat', example: 'He <strong>sat</strong> on the chair.' },
        { infinitive: 'sleep', translation: 'спать', pastSimple: 'slept', pastParticiple: 'slept', example: 'I <strong>slept</strong> well.' },
        { infinitive: 'smell', translation: 'пахнуть', pastSimple: 'smelt/smelled', pastParticiple: 'smelt/smelled', example: 'It <strong>smelled</strong> nice.' },
        { infinitive: 'speak', translation: 'говорить', pastSimple: 'spoke', pastParticiple: 'spoken', example: 'She <strong>spoke</strong> loudly.' },
        { infinitive: 'spend', translation: 'тратить', pastSimple: 'spent', pastParticiple: 'spent', example: 'I <strong>spent</strong> $50.' },
        { infinitive: 'stand', translation: 'стоять', pastSimple: 'stood', pastParticiple: 'stood', example: 'He <strong>stood</strong> still.' },
        { infinitive: 'steal', translation: 'воровать', pastSimple: 'stole', pastParticiple: 'stolen', example: 'Someone <strong>stole</strong> my bag.' },
        { infinitive: 'sting', translation: 'жалить', pastSimple: 'stung', pastParticiple: 'stung', example: 'A bee <strong>stung</strong> me.' },
        { infinitive: 'swim', translation: 'плавать', pastSimple: 'swam', pastParticiple: 'swum', example: 'She <strong>swam</strong> in the pool.' },
        { infinitive: 'take', translation: 'брать', pastSimple: 'took', pastParticiple: 'taken', example: 'I <strong>took</strong> a taxi.' },
        { infinitive: 'teach', translation: 'учить', pastSimple: 'taught', pastParticiple: 'taught', example: 'She <strong>taught</strong> me math.' },
        { infinitive: 'tear', translation: 'рвать', pastSimple: 'tore', pastParticiple: 'torn', example: 'He <strong>tore</strong> the paper.' },
        { infinitive: 'tell', translation: 'рассказывать', pastSimple: 'told', pastParticiple: 'told', example: 'She <strong>told</strong> me a story.' },
        { infinitive: 'think', translation: 'думать', pastSimple: 'thought', pastParticiple: 'thought', example: 'I <strong>thought</strong> about it.' },
        { infinitive: 'throw', translation: 'бросать', pastSimple: 'threw', pastParticiple: 'thrown', example: 'He <strong>threw</strong> the ball.' },
        { infinitive: 'wake', translation: 'просыпаться', pastSimple: 'woke/waked', pastParticiple: 'woken/waked', example: 'I <strong>woke</strong> up early.' },
        { infinitive: 'wear', translation: 'носить', pastSimple: 'wore', pastParticiple: 'worn', example: 'She <strong>wore</strong> a dress.' },
        { infinitive: 'win', translation: 'побеждать', pastSimple: 'won', pastParticiple: 'won', example: 'We <strong>won</strong> the game!' },
        { infinitive: 'write', translation: 'писать', pastSimple: 'wrote', pastParticiple: 'written', example: 'He <strong>wrote</strong> a letter.' }
    ],
    text1: [
        { infinitive: 'environment', translation: 'окружающая среда', example: 'Protect the <strong>environment</strong>.' },
        { infinitive: 'modern', translation: 'современный', example: '<strong>Modern</strong> technology is fast.' },
        { infinitive: 'factors', translation: 'факторы', example: 'Many <strong>factors</strong> affect health.' },
        { infinitive: 'well-being', translation: 'благополучие', example: 'Focus on your <strong>well-being</strong>.' },
        { infinitive: 'planet', translation: 'планета', example: 'Earth is our <strong>planet</strong>.' },
        { infinitive: 'jeopardy', translation: 'опасность', example: 'Lives are in <strong>jeopardy</strong>.' },
        { infinitive: 'opinion', translation: 'мнение', example: 'What is your <strong>opinion</strong>?' },
        { infinitive: 'natural', translation: 'природный', example: 'Use <strong>natural</strong> resources.' },
        { infinitive: 'occurrence', translation: 'явление', example: 'A rare <strong>occurrence</strong>.' },
        { infinitive: 'human beings', translation: 'человеческие существа', example: 'We are <strong>human beings</strong>.' },
        { infinitive: 'impact', translation: 'влияние', example: 'A huge <strong>impact</strong> on nature.' },
        { infinitive: 'consideration', translation: 'рассмотрение', example: 'Take into <strong>consideration</strong>.' },
        { infinitive: 'global warming', translation: 'глобальное потепление', example: 'Stop <strong>global warming</strong>.' },
        { infinitive: 'climate change', translation: 'изменение климата', example: 'Fight <strong>climate change</strong>.' },
        { infinitive: 'contributing', translation: 'способствующий', example: '<strong>Contributing</strong> factors.' },
        { infinitive: 'damage', translation: 'ущерб', example: 'Causing serious <strong>damage</strong>.' },
        { infinitive: 'melting', translation: 'таяние', example: 'The ice is <strong>melting</strong>.' },
        { infinitive: 'ice caps', translation: 'ледяные шапки', example: 'Polar <strong>ice caps</strong>.' },
        { infinitive: 'sea levels', translation: 'уровень моря', example: 'Rising <strong>sea levels</strong>.' },
        { infinitive: 'storms', translation: 'штормы', example: 'Severe <strong>storms</strong>.' },
        { infinitive: 'droughts', translation: 'засухи', example: 'Long periods of <strong>droughts</strong>.' },
        { infinitive: 'flooding', translation: 'наводнение', example: 'Risk of <strong>flooding</strong>.' },
        { infinitive: 'pollution', translation: 'загрязнение', example: 'Air <strong>pollution</strong>.' },
        { infinitive: 'emissions', translation: 'выбросы', example: 'Reduce gas <strong>emissions</strong>.' },
        { infinitive: 'carbon dioxide', translation: 'углекислый газ', example: '<strong>Carbon dioxide</strong> levels.' },
        { infinitive: 'burning', translation: 'сжигание', example: '<strong>Burning</strong> wood.' },
        { infinitive: 'fossil fuels', translation: 'ископаемое топливо', example: 'Using <strong>fossil fuels</strong>.' },
        { infinitive: 'chemicals', translation: 'химикаты', example: 'Toxic <strong>chemicals</strong>.' },
        { infinitive: 'waste disposal', translation: 'утилизация отходов', example: 'Proper <strong>waste disposal</strong>.' },
        { infinitive: 'atmosphere', translation: 'атмосфера', example: 'Earth\'s <strong>atmosphere</strong>.' },
        { infinitive: 'smog', translation: 'смог', example: 'The city is covered in <strong>smog</strong>.' },
        { infinitive: 'precipitation', translation: 'осадки', example: 'Heavy <strong>precipitation</strong>.' },
        { infinitive: 'natural resources', translation: 'природные ресурсы', example: 'Save <strong>natural resources</strong>.' },
        { infinitive: 'mining', translation: 'добыча', example: 'Coal <strong>mining</strong>.' },
        { infinitive: 'deforestation', translation: 'вырубка лесов', example: 'Stop <strong>deforestation</strong>.' },
        { infinitive: 'water resources', translation: 'водные ресурсы', example: 'Clean <strong>water resources</strong>.' },
        { infinitive: 'oil spills', translation: 'разливы нефти', example: 'Major <strong>oil spills</strong>.' },
        { infinitive: 'habitats', translation: 'места обитания', example: 'Natural <strong>habitats</strong>.' },
        { infinitive: 'endangered species', translation: 'исчезающие виды', example: 'Save <strong>endangered species</strong>.' },
        { infinitive: 'extinction', translation: 'вымирание', example: 'Face <strong>extinction</strong>.' },
        { infinitive: 'sustainable', translation: 'устойчивый', example: '<strong>Sustainable</strong> development.' },
        { infinitive: 'recycle', translation: 'перерабатывать', example: 'Please <strong>recycle</strong> paper.' },
        { infinitive: 'reduce', translation: 'уменьшать', example: '<strong>Reduce</strong> waste.' },
        { infinitive: 'reuse', translation: 'повторно использовать', example: '<strong>Reuse</strong> bottles.' },
        { infinitive: 'habits', translation: 'привычки', example: 'Good <strong>habits</strong>.' },
        { infinitive: 'uninhabitable', translation: 'непригодный для жизни', example: 'Becomes <strong>uninhabitable</strong>.' },
        { infinitive: 'repercussions', translation: 'последствия', example: 'Serious <strong>repercussions</strong>.' },
        { infinitive: 'strategies', translation: 'стратегии', example: 'New <strong>strategies</strong>.' },
        { infinitive: 'improper', translation: 'неправильный', example: '<strong>Improper</strong> use.' }
    ],
    text2: [
        { infinitive: 'university', translation: 'университет', example: 'Study at a <strong>university</strong>.' },
        { infinitive: 'institution', translation: 'учреждение', example: 'Educational <strong>institution</strong>.' },
        { infinitive: 'best-known', translation: 'наиболее известный', example: 'The <strong>best-known</strong> writer.' },
        { infinitive: 'located', translation: 'расположенный', example: '<strong>Located</strong> in London.' },
        { infinitive: 'autonomous', translation: 'автономный', example: 'An <strong>autonomous</strong> region.' },
        { infinitive: 'governing body', translation: 'руководящий орган', example: 'The school\'s <strong>governing body</strong>.' },
        { infinitive: 'college', translation: 'колледж', example: 'Go to <strong>college</strong>.' },
        { infinitive: 'regulations', translation: 'правила', example: 'Follow the <strong>regulations</strong>.' },
        { infinitive: 'course', translation: 'курс', example: 'Take a <strong>course</strong>.' },
        { infinitive: 'grants', translation: 'гранты', example: 'Student <strong>grants</strong>.' },
        { infinitive: 'academic year', translation: 'учебный год', example: 'The <strong>academic year</strong> starts in Sept.' },
        { infinitive: 'terms', translation: 'триместры/семестры', example: 'Three <strong>terms</strong> a year.' },
        { infinitive: 'progress', translation: 'успеваемость', example: 'Check your <strong>progress</strong>.' },
        { infinitive: 'assessment', translation: 'оценивание', example: 'Final <strong>assessment</strong>.' },
        { infinitive: 'examinations', translation: 'экзамены', example: 'Pass the <strong>examinations</strong>.' },
        { infinitive: 'degree', translation: 'степень', example: 'Get a <strong>degree</strong>.' },
        { infinitive: 'Bachelor’s degree', translation: 'степень бакалавра', example: 'Earn a <strong>Bachelor’s degree</strong>.' },
        { infinitive: 'facilities', translation: 'условия', example: 'Sports <strong>facilities</strong>.' },
        { infinitive: 'research', translation: 'исследования', example: 'Scientific <strong>research</strong>.' },
        { infinitive: 'tuition fees', translation: 'плата за обучение', example: 'High <strong>tuition fees</strong>.' },
        { infinitive: 'considerably', translation: 'значительно', example: 'It costs <strong>considerably</strong> more.' },
        { infinitive: 'national system', translation: 'национальная система', example: 'The <strong>national system</strong>.' },
        { infinitive: 'higher education', translation: 'высшее образование', example: '<strong>Higher education</strong> is important.' },
        { infinitive: 'technological', translation: 'технологический', example: '<strong>Technological</strong> advances.' },
        { infinitive: 'average', translation: 'средний', example: 'Above <strong>average</strong>.' },
        { infinitive: 'semester', translation: 'семестр', example: 'Fall <strong>semester</strong>.' },
        { infinitive: 'freshmen', translation: 'первокурсники', example: 'Welcome <strong>freshmen</strong>.' },
        { infinitive: 'major', translation: 'специальность', example: 'My <strong>major</strong> is biology.' },
        { infinitive: 'subject', translation: 'предмет', example: 'Favorite <strong>subject</strong>.' },
        { infinitive: 'Master’s degree', translation: 'степень магистра', example: 'Hold a <strong>Master’s degree</strong>.' },
        { infinitive: 'scale', translation: 'шкала', example: 'On a large <strong>scale</strong>.' },
        { infinitive: 'level of achievement', translation: 'уровень успеваемости', example: 'High <strong>level of achievement</strong>.' },
        { infinitive: 'highest mark', translation: 'высшая оценка', example: 'Got the <strong>highest mark</strong>.' },
        { infinitive: 'fail', translation: 'провалить', example: 'Don\'t <strong>fail</strong> the exam.' },
        { infinitive: 'lectures', translation: 'лекции', example: 'Attend <strong>lectures</strong>.' },
        { infinitive: 'discussions', translation: 'обсуждения', example: 'Group <strong>discussions</strong>.' },
        { infinitive: 'laboratories', translation: 'лаборатории', example: 'Work in <strong>laboratories</strong>.' },
        { infinitive: 'seminars', translation: 'семинары', example: 'Weekly <strong>seminars</strong>.' },
        { infinitive: 'traditional', translation: 'традиционный', example: '<strong>Traditional</strong> methods.' },
        { infinitive: 'ancient', translation: 'древний', example: 'An <strong>ancient</strong> building.' },
        { infinitive: 'responsible', translation: 'ответственный', example: 'Be <strong>responsible</strong>.' },
        { infinitive: 'varies', translation: 'варьируется', example: 'The price <strong>varies</strong>.' },
        { infinitive: 'institutions', translation: 'учреждения', example: 'Public <strong>institutions</strong>.' },
        { infinitive: 'choice', translation: 'выбор', example: 'Make a <strong>choice</strong>.' },
        { infinitive: 'provide', translation: 'предоставлять', example: '<strong>Provide</strong> support.' },
        { infinitive: 'campuses', translation: 'кампусы', example: 'University <strong>campuses</strong>.' },
        { infinitive: 'students', translation: 'студенты', example: 'Many <strong>students</strong>.' },
        { infinitive: 'course of study', translation: 'учебная программа', example: 'Plan your <strong>course of study</strong>.' },
        { infinitive: 'charge', translation: 'взимать плату', example: 'They <strong>charge</strong> fees.' },
        { infinitive: 'grant', translation: 'грант', example: 'Apply for a <strong>grant</strong>.' }
    ],
    text3: [
        { infinitive: 'development', translation: 'развитие', example: 'Economic <strong>development</strong>.' },
        { infinitive: 'progress', translation: 'прогресс', example: 'Make <strong>progress</strong>.' },
        { infinitive: 'specialists', translation: 'специалисты', example: 'Qualified <strong>specialists</strong>.' },
        { infinitive: 'standards', translation: 'стандарты', example: 'High <strong>standards</strong>.' },
        { infinitive: 'living', translation: 'уровень жизни', example: 'Standard of <strong>living</strong>.' },
        { infinitive: 'changing', translation: 'меняющийся', example: 'A <strong>changing</strong> world.' },
        { infinitive: 'continuous', translation: 'непрерывный', example: '<strong>Continuous</strong> learning.' },
        { infinitive: 'adoption', translation: 'принятие', example: 'The <strong>adoption</strong> of new laws.' },
        { infinitive: 'contemporary', translation: 'современный', example: '<strong>Contemporary</strong> art.' },
        { infinitive: 'recognized', translation: 'признанный', example: 'Internationally <strong>recognized</strong>.' },
        { infinitive: 'methods', translation: 'методы', example: 'Teaching <strong>methods</strong>.' },
        { infinitive: 'instruction', translation: 'обучение', example: 'Language <strong>instruction</strong>.' },
        { infinitive: 'information', translation: 'информация', example: 'Useful <strong>information</strong>.' },
        { infinitive: 'explosion', translation: 'взрыв/бурный рост', example: 'Information <strong>explosion</strong>.' },
        { infinitive: 'natural sciences', translation: 'естественные науки', example: 'Study <strong>natural sciences</strong>.' },
        { infinitive: 'applied sciences', translation: 'прикладные науки', example: 'Focus on <strong>applied sciences</strong>.' },
        { infinitive: 'increase', translation: 'увеличение', example: 'An <strong>increase</strong> in jobs.' },
        { infinitive: 'approaches', translation: 'подходы', example: 'New <strong>approaches</strong>.' },
        { infinitive: 'distance education', translation: 'дистанционное образование', example: '<strong>Distance education</strong> is popular.' },
        { infinitive: 'system', translation: 'система', example: 'The school <strong>system</strong>.' },
        { infinitive: 'enables', translation: 'позволяет', example: 'It <strong>enables</strong> us to work.' },
        { infinitive: 'foundation', translation: 'основа', example: 'A strong <strong>foundation</strong>.' },
        { infinitive: 'field', translation: 'область', example: 'In the <strong>field</strong> of science.' },
        { infinitive: 'video courses', translation: 'видеокурсы', example: 'Watch <strong>video courses</strong>.' },
        { infinitive: 'videoconferencing', translation: 'видеоконференции', example: 'Use <strong>videoconferencing</strong>.' },
        { infinitive: 'mathematics', translation: 'математика', example: 'Solve <strong>mathematics</strong> problems.' },
        { infinitive: 'physics', translation: 'физика', example: 'Laws of <strong>physics</strong>.' },
        { infinitive: 'chemistry', translation: 'химия', example: 'Study <strong>chemistry</strong>.' },
        { infinitive: 'drawing', translation: 'черчение', example: 'Technical <strong>drawing</strong>.' },
        { infinitive: 'engineering', translation: 'инженерия', example: 'Software <strong>engineering</strong>.' },
        { infinitive: 'broadened', translation: 'расширенный', example: '<strong>Broadened</strong> horizons.' },
        { infinitive: 'foreign languages', translation: 'иностранные языки', example: 'Speak <strong>foreign languages</strong>.' },
        { infinitive: 'economics', translation: 'экономика', example: 'Global <strong>economics</strong>.' },
        { infinitive: 'advanced', translation: 'продвинутый', example: '<strong>Advanced</strong> technology.' },
        { infinitive: 'specialization', translation: 'специализация', example: 'Narrow <strong>specialization</strong>.' },
        { infinitive: 'enterprises', translation: 'предприятия', example: 'Local <strong>enterprises</strong>.' },
        { infinitive: 'hostels', translation: 'общежития', example: 'Live in <strong>hostels</strong>.' },
        { infinitive: 'excellent', translation: 'отличный', example: '<strong>Excellent</strong> results.' },
        { infinitive: 'process', translation: 'процесс', example: 'Learning <strong>process</strong>.' },
        { infinitive: 'culture', translation: 'культура', example: 'Russian <strong>culture</strong>.' },
        { infinitive: 'preserved', translation: 'сохранённый', example: 'Well <strong>preserved</strong>.' },
        { infinitive: 'values', translation: 'ценности', example: 'Moral <strong>values</strong>.' },
        { infinitive: 'exchange', translation: 'обмен', example: 'Student <strong>exchange</strong>.' },
        { infinitive: 'success', translation: 'успех', example: 'Achieve <strong>success</strong>.' }
    ],
    text4: [
        { infinitive: 'communication', translation: 'коммуникация', example: 'Effective <strong>communication</strong>.' },
        { infinitive: 'life', translation: 'жизнь', example: 'Daily <strong>life</strong>.' },
        { infinitive: 'people', translation: 'люди', example: 'Many <strong>people</strong>.' },
        { infinitive: 'process', translation: 'процесс', example: 'A long <strong>process</strong>.' },
        { infinitive: 'sender', translation: 'отправитель', example: 'The <strong>sender</strong> of the letter.' },
        { infinitive: 'receiver', translation: 'получатель', example: 'The <strong>receiver</strong> of the message.' },
        { infinitive: 'medium', translation: 'средство', example: 'A <strong>medium</strong> of exchange.' },
        { infinitive: 'message', translation: 'сообщение', example: 'Send a <strong>message</strong>.' },
        { infinitive: 'feedback', translation: 'обратная связь', example: 'Give <strong>feedback</strong>.' },
        { infinitive: 'explanation', translation: 'объяснение', example: 'A clear <strong>explanation</strong>.' },
        { infinitive: 'common', translation: 'обычный', example: 'A <strong>common</strong> problem.' },
        { infinitive: 'person', translation: 'человек', example: 'A nice <strong>person</strong>.' },
        { infinitive: 'age', translation: 'возраст', example: 'At the <strong>age</strong> of ten.' },
        { infinitive: 'sex', translation: 'пол', example: 'Male or female <strong>sex</strong>.' },
        { infinitive: 'position', translation: 'положение', example: 'Social <strong>position</strong>.' },
        { infinitive: 'important', translation: 'важный', example: 'An <strong>important</strong> task.' },
        { infinitive: 'necessity', translation: 'необходимость', example: 'Absolute <strong>necessity</strong>.' },
        { infinitive: 'human', translation: 'человек', example: '<strong>Human</strong> nature.' },
        { infinitive: 'being', translation: 'существо', example: 'A living <strong>being</strong>.' },
        { infinitive: 'years', translation: 'годы', example: 'For many <strong>years</strong>.' },
        { infinitive: 'gestures', translation: 'жесты', example: 'Use <strong>gestures</strong>.' },
        { infinitive: 'sounds', translation: 'звуки', example: 'Loud <strong>sounds</strong>.' },
        { infinitive: 'pictures', translation: 'изображения', example: 'Draw <strong>pictures</strong>.' },
        { infinitive: 'imagine', translation: 'представить', example: '<strong>Imagine</strong> a world.' },
        { infinitive: 'dull', translation: 'скучный', example: 'A <strong>dull</strong> day.' },
        { infinitive: 'unemotional', translation: 'безэмоциональный', example: 'An <strong>unemotional</strong> voice.' },
        { infinitive: 'robots', translation: 'роботы', example: '<strong>Robots</strong> work here.' },
        { infinitive: 'feelings', translation: 'чувства', example: 'Hurt my <strong>feelings</strong>.' },
        { infinitive: 'emotions', translation: 'эмоции', example: 'Show <strong>emotions</strong>.' },
        { infinitive: 'relatives', translation: 'родственники', example: 'Visit <strong>relatives</strong>.' },
        { infinitive: 'close', translation: 'близкие', example: '<strong>Close</strong> friends.' },
        { infinitive: 'understand', translation: 'понимать', example: 'I <strong>understand</strong> you.' },
        { infinitive: 'eyes', translation: 'глаза', example: 'Blue <strong>eyes</strong>.' },
        { infinitive: 'gadgets', translation: 'гаджеты', example: 'New <strong>gadgets</strong>.' },
        { infinitive: 'opportunity', translation: 'возможность', example: 'A good <strong>opportunity</strong>.' },
        { infinitive: 'mobile phone', translation: 'мобильный телефон', example: 'Use a <strong>mobile phone</strong>.' },
        { infinitive: 'marks', translation: 'знаки', example: 'Punctuation <strong>marks</strong>.' },
        { infinitive: 'smiles', translation: 'улыбки', example: 'Full of <strong>smiles</strong>.' },
        { infinitive: 'program', translation: 'программа', example: 'TV <strong>program</strong>.' },
        { infinitive: 'partners', translation: 'партнёры', example: 'Business <strong>partners</strong>.' },
        { infinitive: 'useful', translation: 'полезный', example: '<strong>Useful</strong> advice.' },
        { infinitive: 'moment', translation: 'момент', example: 'Wait a <strong>moment</strong>.' },
        { infinitive: 'treasure', translation: 'сокровище', example: 'Hidden <strong>treasure</strong>.' },
        { infinitive: 'stimulating', translation: 'стимулирующий', example: '<strong>Stimulating</strong> talk.' },
        { infinitive: 'black coffee', translation: 'чёрный кофе', example: 'Drink <strong>black coffee</strong>.' },
        { infinitive: 'sleep', translation: 'сон', example: 'Get some <strong>sleep</strong>.' }
    ],
    text5: [
        { infinitive: 'Environmental', translation: 'экологический', example: '<strong>Environmental</strong> issues.' },
        { infinitive: 'Pollution', translation: 'загрязнение', example: 'Stop <strong>pollution</strong>.' },
        { infinitive: 'Concern', translation: 'проблема, тревога', example: 'A major <strong>concern</strong>.' },
        { infinitive: 'Harmful', translation: 'вредный', example: '<strong>Harmful</strong> substances.' },
        { infinitive: 'Substances', translation: 'вещества', example: 'Chemical <strong>substances</strong>.' },
        { infinitive: 'Materials', translation: 'материалы', example: 'Building <strong>materials</strong>.' },
        { infinitive: 'Ecosystems', translation: 'экосистемы', example: 'Fragile <strong>ecosystems</strong>.' },
        { infinitive: 'Health', translation: 'здоровье', example: 'Good <strong>health</strong>.' },
        { infinitive: 'Organisms', translation: 'организмы', example: 'Living <strong>organisms</strong>.' },
        { infinitive: 'Air', translation: 'воздух', example: 'Fresh <strong>air</strong>.' },
        { infinitive: 'Release', translation: 'выброс', example: '<strong>Release</strong> of gas.' },
        { infinitive: 'Gases', translation: 'газы', example: 'Greenhouse <strong>gases</strong>.' },
        { infinitive: 'Particles', translation: 'частицы', example: 'Dust <strong>particles</strong>.' },
        { infinitive: 'Atmosphere', translation: 'атмосфера', example: 'Upper <strong>atmosphere</strong>.' },
        { infinitive: 'Combustion', translation: 'сгорание', example: 'Fuel <strong>combustion</strong>.' },
        { infinitive: 'Industrial', translation: 'промышленный', example: '<strong>Industrial</strong> area.' },
        { infinitive: 'Transportation', translation: 'транспорт', example: 'Public <strong>transportation</strong>.' },
        { infinitive: 'Impact', translation: 'воздействие', example: 'Negative <strong>impact</strong>.' },
        { infinitive: 'Respiratory', translation: 'дыхательный', example: '<strong>Respiratory</strong> system.' },
        { infinitive: 'Cardiovascular', translation: 'сердечно-сосудистый', example: '<strong>Cardiovascular</strong> disease.' },
        { infinitive: 'Diseases', translation: 'заболевания', example: 'Cure <strong>diseases</strong>.' },
        { infinitive: 'Water', translation: 'вода', example: 'Drink <strong>water</strong>.' },
        { infinitive: 'Toxic', translation: 'токсичный', example: '<strong>Toxic</strong> waste.' },
        { infinitive: 'Contamination', translation: 'загрязнение', example: 'Food <strong>contamination</strong>.' },
        { infinitive: 'Biodiversity', translation: 'биоразнообразие', example: 'Loss of <strong>biodiversity</strong>.' },
        { infinitive: 'Soil', translation: 'почва', example: 'Fertile <strong>soil</strong>.' },
        { infinitive: 'Fertility', translation: 'плодородие', example: 'Soil <strong>fertility</strong>.' },
        { infinitive: 'Pesticides', translation: 'пестициды', example: 'Use <strong>pesticides</strong>.' },
        { infinitive: 'Vegetation', translation: 'растительность', example: 'Dense <strong>vegetation</strong>.' },
        { infinitive: 'Noise', translation: 'шум', example: 'Loud <strong>noise</strong>.' },
        { infinitive: 'Excessive', translation: 'чрезмерный', example: '<strong>Excessive</strong> speed.' },
        { infinitive: 'Disturbances', translation: 'нарушения', example: 'Sleep <strong>disturbances</strong>.' },
        { infinitive: 'Consequences', translation: 'последствия', example: 'Face <strong>consequences</strong>.' },
        { infinitive: 'Governments', translation: 'правительства', example: 'Local <strong>governments</strong>.' },
        { infinitive: 'Businesses', translation: 'бизнес-структуры', example: 'Small <strong>businesses</strong>.' },
        { infinitive: 'Regulate', translation: 'регулировать', example: '<strong>Regulate</strong> prices.' },
        { infinitive: 'Monitor', translation: 'контролировать', example: '<strong>Monitor</strong> progress.' },
        { infinitive: 'Responsibility', translation: 'ответственность', example: 'Take <strong>responsibility</strong>.' },
        { infinitive: 'Recycling', translation: 'переработка', example: '<strong>Recycling</strong> bin.' },
        { infinitive: 'Energy', translation: 'энергия', example: 'Solar <strong>energy</strong>.' },
        { infinitive: 'Consumption', translation: 'потребление', example: 'Water <strong>consumption</strong>.' },
        { infinitive: 'Challenge', translation: 'вызов', example: 'A big <strong>challenge</strong>.' },
        { infinitive: 'Generations', translation: 'поколения', example: 'Future <strong>generations</strong>.' },
        { infinitive: 'Future', translation: 'будущее', example: 'Bright <strong>future</strong>.' }
    ]
};