// ============ Verbs Data with Examples ============
export const datasets = {
    verbs: [
        { infinitive: 'be', translation: 'быть', pastSimple: 'was/were', pastParticiple: 'been', example: 'I <strong>was</strong> at home yesterday.' },
        { infinitive: 'beat', translation: 'бить', pastSimple: 'beat', pastParticiple: 'beaten', example: 'Our team <strong>beat</strong> them 3-0.' },
        { infinitive: 'become', translation: 'становиться', pastSimple: 'became', pastParticiple: 'become', example: 'She <strong>became</strong> a doctor.' },
        { infinitive: 'begin', translation: 'начинать', pastSimple: 'began', pastParticiple: 'begun', example: 'The movie <strong>began</strong> at 8 PM.' },
        { infinitive: 'bite', translation: 'кусать', pastSimple: 'bit', pastParticiple: 'bitten', example: 'The dog <strong>bit</strong> me!' },
        { infinitive: 'blow', translation: 'дуть', pastSimple: 'blew', pastParticiple: 'blown', example: 'The wind <strong>blew</strong> hard.' },
        { infinitive: 'break', translation: 'ломать(ся)', pastSimple: 'broke', pastParticiple: 'broken', example: 'He <strong>broke</strong> the window.' },
        { infinitive: 'bring', translation: 'приносить', pastSimple: 'brought', pastParticiple: 'brought', example: 'She <strong>brought</strong> me flowers.' },
        { infinitive: 'build', translation: 'строить', pastSimple: 'built', pastParticiple: 'built', example: 'They <strong>built</strong> a new house.' },
        { infinitive: 'burst', translation: 'разрывать(ся)', pastSimple: 'burst', pastParticiple: 'burst', example: 'The balloon <strong>burst</strong> suddenly.' },
        { infinitive: 'buy', translation: 'покупать', pastSimple: 'bought', pastParticiple: 'bought', example: 'I <strong>bought</strong> a new car.' },
        { infinitive: 'catch', translation: 'ловить', pastSimple: 'caught', pastParticiple: 'caught', example: 'He <strong>caught</strong> the ball.' },
        { infinitive: 'choose', translation: 'выбирать', pastSimple: 'chose', pastParticiple: 'chosen', example: 'She <strong>chose</strong> the red dress.' },
        { infinitive: 'come', translation: 'приходить', pastSimple: 'came', pastParticiple: 'come', example: 'He <strong>came</strong> home late.' },
        { infinitive: 'cost', translation: 'стоить', pastSimple: 'cost', pastParticiple: 'cost', example: 'It <strong>cost</strong> $100.' },
        { infinitive: 'deal', translation: 'раздавать', pastSimple: 'dealt', pastParticiple: 'dealt', example: 'He <strong>dealt</strong> the cards.' },
        { infinitive: 'dig', translation: 'копать(ся)', pastSimple: 'dug', pastParticiple: 'dug', example: 'The dog <strong>dug</strong> a hole.' },
        { infinitive: 'do', translation: 'делать', pastSimple: 'did', pastParticiple: 'done', example: 'I <strong>did</strong> my homework.' },
        { infinitive: 'draw', translation: 'рисовать', pastSimple: 'drew', pastParticiple: 'drawn', example: 'She <strong>drew</strong> a beautiful picture.' },
        { infinitive: 'drink', translation: 'пить', pastSimple: 'drank', pastParticiple: 'drunk', example: 'He <strong>drank</strong> coffee.' },
        { infinitive: 'drive', translation: 'ехать', pastSimple: 'drove', pastParticiple: 'driven', example: 'She <strong>drove</strong> to work.' },
        { infinitive: 'eat', translation: 'есть', pastSimple: 'ate', pastParticiple: 'eaten', example: 'We <strong>ate</strong> pizza.' },
        { infinitive: 'fall', translation: 'падать', pastSimple: 'fell', pastParticiple: 'fallen', example: 'He <strong>fell</strong> down.' },
        { infinitive: 'feed', translation: 'кормить', pastSimple: 'fed', pastParticiple: 'fed', example: 'She <strong>fed</strong> the cat.' },
        { infinitive: 'feel', translation: 'ощущать', pastSimple: 'felt', pastParticiple: 'felt', example: 'I <strong>felt</strong> happy.' },
        { infinitive: 'fight', translation: 'драться', pastSimple: 'fought', pastParticiple: 'fought', example: 'They <strong>fought</strong> bravely.' },
        { infinitive: 'find', translation: 'находить', pastSimple: 'found', pastParticiple: 'found', example: 'I <strong>found</strong> my keys.' },
        { infinitive: 'fly', translation: 'летать', pastSimple: 'flew', pastParticiple: 'flown', example: 'The bird <strong>flew</strong> away.' },
        { infinitive: 'forget', translation: 'забывать', pastSimple: 'forgot', pastParticiple: 'forgotten', example: 'I <strong>forgot</strong> her name.' },
        { infinitive: 'freeze', translation: 'замораживать', pastSimple: 'froze', pastParticiple: 'frozen', example: 'The lake <strong>froze</strong> in winter.' },
        { infinitive: 'get', translation: 'получать', pastSimple: 'got', pastParticiple: 'got/gotten', example: 'I <strong>got</strong> a gift.' },
        { infinitive: 'give', translation: 'давать', pastSimple: 'gave', pastParticiple: 'given', example: 'She <strong>gave</strong> me advice.' },
        { infinitive: 'go', translation: 'идти', pastSimple: 'went', pastParticiple: 'gone', example: 'He <strong>went</strong> to school.' },
        { infinitive: 'grow', translation: 'расти', pastSimple: 'grew', pastParticiple: 'grown', example: 'The tree <strong>grew</strong> tall.' },
        { infinitive: 'hang', translation: 'висеть', pastSimple: 'hung/hanged', pastParticiple: 'hung/hanged', example: 'She <strong>hung</strong> the picture.' },
        { infinitive: 'have', translation: 'иметь', pastSimple: 'had', pastParticiple: 'had', example: 'I <strong>had</strong> breakfast.' },
        { infinitive: 'hear', translation: 'слышать', pastSimple: 'heard', pastParticiple: 'heard', example: 'I <strong>heard</strong> the news.' },
        { infinitive: 'hide', translation: 'прятать(ся)', pastSimple: 'hid', pastParticiple: 'hidden', example: 'The cat <strong>hid</strong> under the bed.' },
        { infinitive: 'hit', translation: 'ударять', pastSimple: 'hit', pastParticiple: 'hit', example: 'He <strong>hit</strong> the ball.' },
        { infinitive: 'hold', translation: 'держать', pastSimple: 'held', pastParticiple: 'held', example: 'She <strong>held</strong> my hand.' },
        { infinitive: 'keep', translation: 'хранить', pastSimple: 'kept', pastParticiple: 'kept', example: 'I <strong>kept</strong> the secret.' },
        { infinitive: 'know', translation: 'знать', pastSimple: 'knew', pastParticiple: 'known', example: 'I <strong>knew</strong> the answer.' },
        { infinitive: 'lay', translation: 'класть', pastSimple: 'laid', pastParticiple: 'laid', example: 'She <strong>laid</strong> the book on the table.' },
        { infinitive: 'lead', translation: 'вести', pastSimple: 'led', pastParticiple: 'led', example: 'He <strong>led</strong> the team.' },
        { infinitive: 'learn', translation: 'учиться', pastSimple: 'learnt/learned', pastParticiple: 'learnt/learned', example: 'I <strong>learned</strong> English.' },
        { infinitive: 'leave', translation: 'уходить', pastSimple: 'left', pastParticiple: 'left', example: 'She <strong>left</strong> early.' },
        { infinitive: 'lend', translation: 'одалживать', pastSimple: 'lent', pastParticiple: 'lent', example: 'He <strong>lent</strong> me money.' },
        { infinitive: 'let', translation: 'разрешать', pastSimple: 'let', pastParticiple: 'let', example: 'They <strong>let</strong> me go.' },
        { infinitive: 'lie', translation: 'лежать', pastSimple: 'lay', pastParticiple: 'lain', example: 'He <strong>lay</strong> on the sofa.' },
        { infinitive: 'lose', translation: 'терять', pastSimple: 'lost', pastParticiple: 'lost', example: 'I <strong>lost</strong> my phone.' },
        { infinitive: 'make', translation: 'делать', pastSimple: 'made', pastParticiple: 'made', example: 'She <strong>made</strong> a cake.' },
        { infinitive: 'mean', translation: 'означать', pastSimple: 'meant', pastParticiple: 'meant', example: 'I <strong>meant</strong> to help.' },
        { infinitive: 'meet', translation: 'встречать', pastSimple: 'met', pastParticiple: 'met', example: 'We <strong>met</strong> at the cafe.' },
        { infinitive: 'pay', translation: 'платить', pastSimple: 'paid', pastParticiple: 'paid', example: 'I <strong>paid</strong> the bill.' },
        { infinitive: 'put', translation: 'класть', pastSimple: 'put', pastParticiple: 'put', example: 'He <strong>put</strong> the book down.' },
        { infinitive: 'read', translation: 'читать', pastSimple: 'read', pastParticiple: 'read', example: 'She <strong>read</strong> a novel.' },
        { infinitive: 'ride', translation: 'ехать верхом', pastSimple: 'rode', pastParticiple: 'ridden', example: 'He <strong>rode</strong> a horse.' },
        { infinitive: 'ring', translation: 'звенеть', pastSimple: 'rang', pastParticiple: 'rung', example: 'The phone <strong>rang</strong>.' },
        { infinitive: 'run', translation: 'бежать', pastSimple: 'ran', pastParticiple: 'run', example: 'She <strong>ran</strong> fast.' },
        { infinitive: 'say', translation: 'сказать', pastSimple: 'said', pastParticiple: 'said', example: 'He <strong>said</strong> hello.' },
        { infinitive: 'see', translation: 'видеть', pastSimple: 'saw', pastParticiple: 'seen', example: 'I <strong>saw</strong> a bird.' },
        { infinitive: 'seek', translation: 'искать', pastSimple: 'sought', pastParticiple: 'sought', example: 'She <strong>sought</strong> help.' },
        { infinitive: 'sell', translation: 'продавать', pastSimple: 'sold', pastParticiple: 'sold', example: 'He <strong>sold</strong> his car.' },
        { infinitive: 'send', translation: 'посылать', pastSimple: 'sent', pastParticiple: 'sent', example: 'I <strong>sent</strong> an email.' },
        { infinitive: 'set', translation: 'устанавливать', pastSimple: 'set', pastParticiple: 'set', example: 'She <strong>set</strong> the table.' },
        { infinitive: 'shake', translation: 'трясти', pastSimple: 'shook', pastParticiple: 'shaken', example: 'He <strong>shook</strong> hands.' },
        { infinitive: 'shine', translation: 'светить', pastSimple: 'shone', pastParticiple: 'shone', example: 'The sun <strong>shone</strong> brightly.' },
        { infinitive: 'shoot', translation: 'стрелять', pastSimple: 'shot', pastParticiple: 'shot', example: 'He <strong>shot</strong> the target.' },
        { infinitive: 'show', translation: 'показывать', pastSimple: 'showed', pastParticiple: 'shown', example: 'She <strong>showed</strong> me photos.' },
        { infinitive: 'shut', translation: 'закрывать', pastSimple: 'shut', pastParticiple: 'shut', example: 'He <strong>shut</strong> the door.' },
        { infinitive: 'sing', translation: 'петь', pastSimple: 'sang', pastParticiple: 'sung', example: 'She <strong>sang</strong> beautifully.' },
        { infinitive: 'sit', translation: 'сидеть', pastSimple: 'sat', pastParticiple: 'sat', example: 'He <strong>sat</strong> on the chair.' },
        { infinitive: 'sleep', translation: 'спать', pastSimple: 'slept', pastParticiple: 'slept', example: 'I <strong>slept</strong> well.' },
        { infinitive: 'smell', translation: 'пахнуть', pastSimple: 'smelt/smelled', pastParticiple: 'smelt/smelled', example: 'It <strong>smelled</strong> nice.' },
        { infinitive: 'speak', translation: 'говорить', pastSimple: 'spoke', pastParticiple: 'spoken', example: 'She <strong>spoke</strong> loudly.' },
        { infinitive: 'spend', translation: 'тратить', pastSimple: 'spent', pastParticiple: 'spent', example: 'I <strong>spent</strong> $50.' },
        { infinitive: 'stand', translation: 'стоять', pastSimple: 'stood', pastParticiple: 'stood', example: 'He <strong>stood</strong> still.' },
        { infinitive: 'steal', translation: 'воровать', pastSimple: 'stole', pastParticiple: 'stolen', example: 'Someone <strong>stole</strong> my bag.' },
        { infinitive: 'sting', translation: 'жалить', pastSimple: 'stung', pastParticiple: 'stung', example: 'A bee <strong>stung</strong> me.' },
        { infinitive: 'swim', translation: 'плавать', pastSimple: 'swam', pastParticiple: 'swum', example: 'She <strong>swam</strong> in the pool.' },
        { infinitive: 'take', translation: 'брать', pastSimple: 'took', pastParticiple: 'taken', example: 'I <strong>took</strong> a taxi.' },
        { infinitive: 'teach', translation: 'учить', pastSimple: 'taught', pastParticiple: 'taught', example: 'She <strong>taught</strong> me math.' },
        { infinitive: 'tear', translation: 'рвать', pastSimple: 'tore', pastParticiple: 'torn', example: 'He <strong>tore</strong> the paper.' },
        { infinitive: 'tell', translation: 'рассказывать', pastSimple: 'told', pastParticiple: 'told', example: 'She <strong>told</strong> me a story.' },
        { infinitive: 'think', translation: 'думать', pastSimple: 'thought', pastParticiple: 'thought', example: 'I <strong>thought</strong> about it.' },
        { infinitive: 'throw', translation: 'бросать', pastSimple: 'threw', pastParticiple: 'thrown', example: 'He <strong>threw</strong> the ball.' },
        { infinitive: 'wake', translation: 'просыпаться', pastSimple: 'woke/waked', pastParticiple: 'woken/waked', example: 'I <strong>woke</strong> up early.' },
        { infinitive: 'wear', translation: 'носить', pastSimple: 'wore', pastParticiple: 'worn', example: 'She <strong>wore</strong> a dress.' },
        { infinitive: 'win', translation: 'побеждать', pastSimple: 'won', pastParticiple: 'won', example: 'We <strong>won</strong> the game!' },
        { infinitive: 'write', translation: 'писать', pastSimple: 'wrote', pastParticiple: 'written', example: 'He <strong>wrote</strong> a letter.' }
    ],
    text1: [
        { infinitive: 'environment', translation: 'окружающая среда', example: 'Human beings have a huge impact on the <strong>environment</strong>.' },
        { infinitive: 'modern', translation: 'современный', example: 'In our <strong>modern</strong> world, there are many factors.' },
        { infinitive: 'factors', translation: 'факторы', example: 'There are many <strong>factors</strong> that place the well-being of the planet in jeopardy.' },
        { infinitive: 'well-being', translation: 'благополучие', example: 'Place the <strong>well-being</strong> of the planet in jeopardy.' },
        { infinitive: 'planet', translation: 'планета', example: 'Place the well-being of the <strong>planet</strong> in jeopardy.' },
        { infinitive: 'jeopardy', translation: 'опасность', example: 'Place the well-being of the planet in <strong>jeopardy</strong>.' },
        { infinitive: 'opinion', translation: 'мнение', example: 'Some people have the <strong>opinion</strong> that environmental problems are just a natural occurrence.' },
        { infinitive: 'natural', translation: 'природный', example: 'Environmental problems are just a <strong>natural</strong> occurrence.' },
        { infinitive: 'occurrence', translation: 'явление', example: 'Environmental problems are just a natural <strong>occurrence</strong>.' },
        { infinitive: 'human beings', translation: 'человеческие существа', example: '<strong>Human beings</strong> have a huge impact on the environment.' },
        { infinitive: 'impact', translation: 'влияние', example: 'Human beings have a huge <strong>impact</strong> on the environment.' },
        { infinitive: 'consideration', translation: 'рассмотрение', example: 'Take into <strong>consideration</strong> the following factors.' },
        { infinitive: 'global warming', translation: 'глобальное потепление', example: '<strong>Global warming</strong> is a major contributing factor to environmental damage.' },
        { infinitive: 'climate change', translation: 'изменение климата', example: 'Global warming or <strong>climate change</strong> is a major contributing factor.' },
        { infinitive: 'contributing', translation: 'способствующий', example: 'A major <strong>contributing</strong> factor to environmental damage.' },
        { infinitive: 'damage', translation: 'ущерб', example: 'A major contributing factor to environmental <strong>damage</strong>.' },
        { infinitive: 'melting', translation: 'таяние', example: 'We have seen an increase in <strong>melting</strong> ice caps.' },
        { infinitive: 'ice caps', translation: 'ледяные шапки', example: 'We have seen an increase in melting <strong>ice caps</strong>.' },
        { infinitive: 'sea levels', translation: 'уровень моря', example: 'A rise in <strong>sea levels</strong>.' },
        { infinitive: 'storms', translation: 'штормы', example: 'These weather patterns have caused stronger <strong>storms</strong>.' },
        { infinitive: 'droughts', translation: 'засухи', example: 'Caused stronger storms, <strong>droughts</strong>, and flooding.' },
        { infinitive: 'flooding', translation: 'наводнение', example: 'Caused stronger storms, droughts, and <strong>flooding</strong>.' },
        { infinitive: 'pollution', translation: 'загрязнение', example: 'Air <strong>pollution</strong> is primarily caused as a result of excessive emissions.' },
        { infinitive: 'emissions', translation: 'выбросы', example: 'Unregulated <strong>emissions</strong> of carbon dioxide into the air.' },
        { infinitive: 'carbon dioxide', translation: 'углекислый газ', example: 'Unregulated emissions of <strong>carbon dioxide</strong> into the air.' },
        { infinitive: 'burning', translation: 'сжигание', example: 'Pollutants mostly emerge from the <strong>burning</strong> of fossil fuels.' },
        { infinitive: 'fossil fuels', translation: 'ископаемое топливо', example: 'Pollutants mostly emerge from the burning of <strong>fossil fuels</strong>.' },
        { infinitive: 'chemicals', translation: 'химикаты', example: 'In addition to <strong>chemicals</strong>, toxic substances, and improper waste disposal.' },
        { infinitive: 'waste disposal', translation: 'утилизация отходов', example: 'Improper <strong>waste disposal</strong>.' },
        { infinitive: 'atmosphere', translation: 'атмосфера', example: 'Air pollutants are absorbed into the <strong>atmosphere</strong>.' },
        { infinitive: 'smog', translation: 'смог', example: 'They can cause <strong>smog</strong>, a combination of smoke and fog.' },
        { infinitive: 'precipitation', translation: 'осадки', example: 'Produce acidic <strong>precipitation</strong> in areas far away.' },
        { infinitive: 'natural resources', translation: 'природные ресурсы', example: 'Do not sustainably use their <strong>natural resources</strong>.' },
        { infinitive: 'mining', translation: 'добыча', example: '<strong>Mining</strong> for natural gases.' },
        { infinitive: 'deforestation', translation: 'вырубка лесов', example: '<strong>Deforestation</strong> can have tremendous effects on the environment.' },
        { infinitive: 'water resources', translation: 'водные ресурсы', example: 'Improper use of <strong>water resources</strong>.' },
        { infinitive: 'oil spills', translation: 'разливы нефти', example: 'Their effects can lead to <strong>oil spills</strong>.' },
        { infinitive: 'habitats', translation: 'места обитания', example: 'Their effects can lead to interrupted animal <strong>habitats</strong>.' },
        { infinitive: 'endangered species', translation: 'исчезающие виды', example: 'Witness the extinction of more <strong>endangered species</strong>.' },
        { infinitive: 'extinction', translation: 'вымирание', example: 'We can potentially witness the <strong>extinction</strong> of more endangered species.' },
        { infinitive: 'sustainable', translation: 'устойчивый', example: 'Establishing environmentally <strong>sustainable</strong> habits.' },
        { infinitive: 'recycle', translation: 'перерабатывать', example: 'Reduce, reuse, and <strong>recycle</strong> materials.' },
        { infinitive: 'reduce', translation: 'уменьшать', example: 'Trying to <strong>reduce</strong>, reuse, and recycle materials.' },
        { infinitive: 'reuse', translation: 'повторно использовать', example: 'Trying to reduce, <strong>reuse</strong>, and recycle materials.' },
        { infinitive: 'habits', translation: 'привычки', example: 'Establishing environmentally sustainable <strong>habits</strong>.' },
        { infinitive: 'uninhabitable', translation: 'непригодный для жизни', example: 'A completely <strong>uninhabitable</strong> planet.' },
        { infinitive: 'repercussions', translation: 'последствия', example: 'Consider the <strong>repercussions</strong> of their actions.' },
        { infinitive: 'strategies', translation: 'стратегии', example: 'While these <strong>strategies</strong> often attempt to boost local economies.' },
        { infinitive: 'improper', translation: 'неправильный', example: '<strong>Improper</strong> use of water resources.' }
    ],
    text2: [
        { infinitive: 'university', translation: 'университет', example: 'There are many <strong>university</strong> institutions in the UK.' },
        { infinitive: 'institution', translation: 'учреждение', example: 'Fees are determined by each <strong>institution</strong>.' },
        { infinitive: 'best-known', translation: 'наиболее известный', example: 'The <strong>best-known</strong> universities are in Oxford and Cambridge.' },
        { infinitive: 'located', translation: 'расположенный', example: 'Universities are <strong>located</strong> in many cities.' },
        { infinitive: 'autonomous', translation: 'автономный', example: 'Every university is <strong>autonomous</strong>.' },
        { infinitive: 'governing body', translation: 'руководящий орган', example: 'Each university is responsible to its <strong>governing body</strong>.' },
        { infinitive: 'college', translation: 'колледж', example: 'Many students live in <strong>college</strong> buildings.' },
        { infinitive: 'regulations', translation: 'правила', example: 'Colleges have their own <strong>regulations</strong>.' },
        { infinitive: 'course', translation: 'курс', example: 'Final examinations are held in each <strong>course</strong>.' },
        { infinitive: 'grants', translation: 'гранты', example: 'Most students get government <strong>grants</strong>.' },
        { infinitive: 'academic year', translation: 'учебный год', example: 'The <strong>academic year</strong> runs from October to June.' },
        { infinitive: 'terms', translation: 'триместры/семестры', example: 'The year consists of three 10-week <strong>terms</strong>.' },
        { infinitive: 'progress', translation: 'успеваемость', example: 'The student’s <strong>progress</strong> is evaluated by tests.' },
        { infinitive: 'assessment', translation: 'оценивание', example: 'Tests and term works are part of <strong>assessment</strong>.' },
        { infinitive: 'examinations', translation: 'экзамены', example: 'Students take final <strong>examinations</strong>.' },
        { infinitive: 'degree', translation: 'степень', example: 'After three or four years they get a <strong>degree</strong>.' },
        { infinitive: 'Bachelor’s degree', translation: 'степень бакалавра', example: 'They get a traditional <strong>Bachelor’s degree</strong>.' },
        { infinitive: 'facilities', translation: 'условия', example: 'Universities provide <strong>facilities</strong> for advanced study.' },
        { infinitive: 'research', translation: 'исследования', example: 'Universities provide facilities for <strong>research</strong>.' },
        { infinitive: 'tuition fees', translation: 'плата за обучение', example: '<strong>Tuition fees</strong> may vary from one university to another.' },
        { infinitive: 'considerably', translation: 'значительно', example: 'Tuition fees may vary <strong>considerably</strong>.' },
        { infinitive: 'national system', translation: 'национальная система', example: 'There is no <strong>national system</strong> of higher education in the US.' },
        { infinitive: 'higher education', translation: 'высшее образование', example: '<strong>Higher education</strong> is given in colleges and universities.' },
        { infinitive: 'technological', translation: 'технологический', example: 'There are <strong>technological</strong> institutes and universities.' },
        { infinitive: 'average', translation: 'средний', example: 'The <strong>average</strong> college course is 4 years.' },
        { infinitive: 'semester', translation: 'семестр', example: 'The year has two <strong>semesters</strong>.' },
        { infinitive: 'freshmen', translation: 'первокурсники', example: 'First-year students are called <strong>freshmen</strong>.' },
        { infinitive: 'major', translation: 'специальность', example: 'Students choose a <strong>major</strong> subject.' },
        { infinitive: 'subject', translation: 'предмет', example: 'They take many courses in this <strong>subject</strong>.' },
        { infinitive: 'Master’s degree', translation: 'степень магистра', example: 'After a Bachelor’s degree, they may receive a <strong>Master’s degree</strong>.' },
        { infinitive: 'scale', translation: 'шкала', example: 'Marks are given on a five point <strong>scale</strong>.' },
        { infinitive: 'level of achievement', translation: 'уровень успеваемости', example: 'Letters indicate the <strong>level of achievement</strong>.' },
        { infinitive: 'highest mark', translation: 'высшая оценка', example: '"A" is the <strong>highest mark</strong>.' },
        { infinitive: 'fail', translation: 'провалить', example: 'With an "F", you <strong>fail</strong>.' },
        { infinitive: 'lectures', translation: 'лекции', example: 'Methods of instruction include <strong>lectures</strong>.' },
        { infinitive: 'discussions', translation: 'обсуждения', example: 'Methods of instruction include <strong>discussions</strong>.' },
        { infinitive: 'laboratories', translation: 'лаборатории', example: 'Students do work in <strong>laboratories</strong>.' },
        { infinitive: 'seminars', translation: 'семинары', example: 'Methods include course works or <strong>seminars</strong>.' },
        { infinitive: 'traditional', translation: 'традиционный', example: 'They get a <strong>traditional</strong> Bachelor’s degree.' },
        { infinitive: 'ancient', translation: 'древний', example: 'Students live in <strong>ancient</strong> college buildings.' },
        { infinitive: 'responsible', translation: 'ответственный', example: 'Every university is <strong>responsible</strong> to its governing body.' },
        { infinitive: 'varies', translation: 'варьируется', example: 'Tuition fees <strong>varies</strong> from one university to another.' },
        { infinitive: 'institutions', translation: 'учреждения', example: 'There are many higher educational <strong>institutions</strong>.' },
        { infinitive: 'choice', translation: 'выбор', example: 'Students make a <strong>choice</strong> of major subject.' },
        { infinitive: 'provide', translation: 'предоставлять', example: 'Universities <strong>provide</strong> facilities for research.' },
        { infinitive: 'campuses', translation: 'кампусы', example: 'Colleges and universities have <strong>campuses</strong>.' },
        { infinitive: 'students', translation: 'студенты', example: 'Most <strong>students</strong> on first degree get grants.' },
        { infinitive: 'course of study', translation: 'учебная программа', example: 'The college <strong>course of study</strong> is 4 years.' },
        { infinitive: 'charge', translation: 'взимать плату', example: 'Many colleges <strong>charge</strong> for tuition.' },
        { infinitive: 'grant', translation: 'грант', example: 'A student may get a government <strong>grant</strong>.' }
    ],
    text3: [
        { infinitive: 'development', translation: 'развитие', example: 'For future <strong>development</strong> and progress.' },
        { infinitive: 'progress', translation: 'прогресс', example: 'For future development and <strong>progress</strong>.' },
        { infinitive: 'specialists', translation: 'специалисты', example: 'Highly-qualified <strong>specialists</strong>.' },
        { infinitive: 'standards', translation: 'стандарты', example: '<strong>Standards</strong> of living are steadily changing.' },
        { infinitive: 'living', translation: 'уровень жизни', example: 'Standards of <strong>living</strong> are steadily changing.' },
        { infinitive: 'changing', translation: 'меняющийся', example: 'In our rapidly <strong>changing</strong> world.' },
        { infinitive: 'continuous', translation: 'непрерывный', example: 'Ensuring <strong>continuous</strong> and thorough adoption.' },
        { infinitive: 'adoption', translation: 'принятие', example: 'Thorough <strong>adoption</strong> of the universities to contemporary needs.' },
        { infinitive: 'contemporary', translation: 'современный', example: 'Adoption to <strong>contemporary</strong> needs.' },
        { infinitive: 'recognized', translation: 'признанный', example: 'This need is widely <strong>recognized</strong>.' },
        { infinitive: 'methods', translation: 'методы', example: 'The increase of information requires new <strong>methods</strong>.' },
        { infinitive: 'instruction', translation: 'обучение', example: 'New approaches to students’ training and <strong>instruction</strong>.' },
        { infinitive: 'information', translation: 'информация', example: 'Knowledge and <strong>information</strong> must be taken into consideration.' },
        { infinitive: 'explosion', translation: 'взрыв/бурный рост', example: 'This information <strong>explosion</strong> has affected every field of study.' },
        { infinitive: 'natural sciences', translation: 'естественные науки', example: 'Especially in the <strong>natural sciences</strong>.' },
        { infinitive: 'applied sciences', translation: 'прикладные науки', example: 'And in the <strong>applied sciences</strong> as well.' },
        { infinitive: 'increase', translation: 'увеличение', example: 'The <strong>increase</strong> of information requires new methods.' },
        { infinitive: 'approaches', translation: 'подходы', example: 'New methods and new <strong>approaches</strong>.' },
        { infinitive: 'distance education', translation: 'дистанционное образование', example: 'A <strong>distance education</strong> system is introduced.' },
        { infinitive: 'system', translation: 'система', example: 'At present a new <strong>system</strong> of education is introduced.' },
        { infinitive: 'enables', translation: 'позволяет', example: 'This system <strong>enables</strong> people to get knowledge.' },
        { infinitive: 'foundation', translation: 'основа', example: 'A good <strong>foundation</strong> in the sciences.' },
        { infinitive: 'field', translation: 'область', example: 'Basic to his or her <strong>field</strong> of study.' },
        { infinitive: 'video courses', translation: 'видеокурсы', example: 'From satellite <strong>video courses</strong> to modern videoconferencing.' },
        { infinitive: 'videoconferencing', translation: 'видеоконференции', example: 'To modern <strong>videoconferencing</strong> through personal computers.' },
        { infinitive: 'academic year', translation: 'учебный год', example: 'The <strong>academic year</strong> usually lasts 9 months.' },
        { infinitive: 'term', translation: 'семестр', example: 'Divided into two <strong>terms</strong> (semesters).' },
        { infinitive: 'instructions', translation: 'обучение', example: 'Obtain thorough <strong>instructions</strong> in the fundamental sciences.' },
        { infinitive: 'mathematics', translation: 'математика', example: 'Fundamental sciences of <strong>mathematics</strong>, physics, chemistry.' },
        { infinitive: 'physics', translation: 'физика', example: 'Fundamental sciences of mathematics, <strong>physics</strong>, chemistry.' },
        { infinitive: 'chemistry', translation: 'химия', example: 'Physics, <strong>chemistry</strong> and drawing.' },
        { infinitive: 'drawing', translation: 'черчение', example: 'Chemistry and <strong>drawing</strong>.' },
        { infinitive: 'engineering', translation: 'инженерия', example: 'As well as computer <strong>engineering</strong>.' },
        { infinitive: 'broadened', translation: 'расширенный', example: 'The curricula are enriched and <strong>broadened</strong>.' },
        { infinitive: 'foreign languages', translation: 'иностранные языки', example: 'Such subjects as <strong>foreign languages</strong>, history and economics.' },
        { infinitive: 'economics', translation: 'экономика', example: 'History and <strong>economics</strong>.' },
        { infinitive: 'advanced', translation: 'продвинутый', example: 'Students get more <strong>advanced</strong> knowledge.' },
        { infinitive: 'specialization', translation: 'специализация', example: '<strong>Specialized</strong> study will help students.' },
        { infinitive: 'bachelor’s degree', translation: 'степень бакалавра', example: 'Students will get a <strong>bachelor’s degree</strong>.' },
        { infinitive: 'master’s degree', translation: 'степень магистра', example: 'Study and research get a <strong>master’s degree</strong>.' },
        { infinitive: 'research', translation: 'научная работа', example: 'Further study and <strong>research</strong>.' },
        { infinitive: 'enterprises', translation: 'предприятия', example: 'Sponsored by <strong>enterprises</strong>.' },
        { infinitive: 'hostels', translation: 'общежития', example: 'Universities have their own students’ <strong>hostels</strong>.' },
        { infinitive: 'excellent', translation: 'отличный', example: 'Large and <strong>excellent</strong> sport centers.' },
        { infinitive: 'process', translation: 'процесс', example: 'Education is a <strong>process</strong>.' },
        { infinitive: 'culture', translation: 'культура', example: 'Through which <strong>culture</strong> is preserved.' },
        { infinitive: 'preserved', translation: 'сохранённый', example: 'Culture is <strong>preserved</strong>.' },
        { infinitive: 'values', translation: 'ценности', example: '<strong>Values</strong> are formed.' },
        { infinitive: 'exchange', translation: 'обмен', example: 'Information is <strong>exchanged</strong>.' },
        { infinitive: 'success', translation: 'успех', example: 'Education is the way to <strong>success</strong>.' }
    ],
    text4: [
        { infinitive: 'communication', translation: 'коммуникация', example: 'Do we know what <strong>communication</strong> is?' },
        { infinitive: 'life', translation: 'жизнь', example: 'We talk about <strong>life</strong> every day.' },
        { infinitive: 'people', translation: 'люди', example: 'We communicate with scores of <strong>people</strong>.' },
        { infinitive: 'information', translation: 'информация', example: 'We exchange <strong>information</strong> and feelings.' },
        { infinitive: 'process', translation: 'процесс', example: 'Communication is a <strong>process</strong>.' },
        { infinitive: 'sender', translation: 'отправитель', example: 'A <strong>sender</strong> imparts information.' },
        { infinitive: 'receiver', translation: 'получатель', example: 'The <strong>receiver</strong> decodes the message.' },
        { infinitive: 'medium', translation: 'средство', example: 'It goes via some <strong>medium</strong>.' },
        { infinitive: 'message', translation: 'сообщение', example: 'Send a short <strong>message</strong>.' },
        { infinitive: 'feedback', translation: 'обратная связь', example: 'The receiver gives <strong>feedback</strong>.' },
        { infinitive: 'explanation', translation: 'объяснение', example: 'A scientific <strong>explanation</strong> of the notion.' },
        { infinitive: 'common', translation: 'обычный', example: 'For a <strong>common</strong> person.' },
        { infinitive: 'person', translation: 'человек', example: 'Meet a <strong>person</strong> face to face.' },
        { infinitive: 'age', translation: 'возраст', example: 'Of any <strong>age</strong>.' },
        { infinitive: 'sex', translation: 'пол', example: 'Any <strong>sex</strong>.' },
        { infinitive: 'position', translation: 'положение', example: 'A social <strong>position</strong>.' },
        { infinitive: 'important', translation: 'важный', example: 'One of the most <strong>important</strong> necessities.' },
        { infinitive: 'necessity', translation: 'необходимость', example: 'Communication is a <strong>necessity</strong>.' },
        { infinitive: 'human', translation: 'человек', example: 'Every <strong>human</strong> being needs it.' },
        { infinitive: 'being', translation: 'существо', example: 'Every human <strong>being</strong>.' },
        { infinitive: 'years', translation: 'годы', example: 'Even million <strong>years</strong> ago.' },
        { infinitive: 'gestures', translation: 'жесты', example: 'With the help of <strong>gestures</strong>.' },
        { infinitive: 'sounds', translation: 'звуки', example: 'With <strong>sounds</strong> and pictures.' },
        { infinitive: 'pictures', translation: 'изображения', example: 'With gestures, sounds and <strong>pictures</strong>.' },
        { infinitive: 'imagine', translation: 'представить', example: 'Try to <strong>imagine</strong> life without it.' },
        { infinitive: 'dull', translation: 'скучный', example: 'The picture will be <strong>dull</strong>.' },
        { infinitive: 'unemotional', translation: 'безэмоциональный', example: 'Dull and <strong>unemotional</strong>.' },
        { infinitive: 'robots', translation: 'роботы', example: 'People are replaced by <strong>robots</strong>.' },
        { infinitive: 'feelings', translation: 'чувства', example: 'We exchange our <strong>feelings</strong>.' },
        { infinitive: 'emotions', translation: 'эмоции', example: 'We exchange our <strong>emotions</strong>.' },
        { infinitive: 'relatives', translation: 'родственники', example: 'Our <strong>relatives</strong> can understand us.' },
        { infinitive: 'close', translation: 'близкие', example: 'Our <strong>close</strong> people.' },
        { infinitive: 'understand', translation: 'понимать', example: 'They can <strong>understand</strong> without words.' },
        { infinitive: 'eyes', translation: 'глаза', example: 'Just looking at our <strong>eyes</strong>.' },
        { infinitive: 'modern', translation: 'современный', example: '<strong>Modern</strong> gadgets give us opportunity.' },
        { infinitive: 'gadgets', translation: 'гаджеты', example: '<strong>Gadgets</strong> give us such opportunity.' },
        { infinitive: 'opportunity', translation: 'возможность', example: 'They give us an <strong>opportunity</strong> to communicate.' },
        { infinitive: 'mobile phone', translation: 'мобильный телефон', example: 'Send a message by the <strong>mobile phone</strong>.' },
        { infinitive: 'marks', translation: 'знаки', example: 'Put different <strong>marks</strong> or smiles.' },
        { infinitive: 'smiles', translation: 'улыбки', example: 'Add <strong>smiles</strong> conveying emotions.' },
        { infinitive: 'program', translation: 'программа', example: 'Using the <strong>program</strong> Skype.' },
        { infinitive: 'partners', translation: 'партнёры', example: 'You can see your <strong>partners</strong> face.' },
        { infinitive: 'useful', translation: 'полезный', example: 'Really <strong>useful</strong> things.' },
        { infinitive: 'moment', translation: 'момент', example: 'Enjoy every <strong>moment</strong>.' },
        { infinitive: 'treasure', translation: 'сокровище', example: 'It is a real <strong>treasure</strong>.' },
        { infinitive: 'stimulating', translation: 'стимулирующий', example: 'Good communication is <strong>stimulating</strong>.' },
        { infinitive: 'black coffee', translation: 'чёрный кофе', example: 'As <strong>black coffee</strong>.' },
        { infinitive: 'sleep', translation: 'сон', example: 'Hard to <strong>sleep</strong> after.' }
    ],
    text5: [
        { infinitive: 'Environmental', translation: 'экологический', example: '<strong>Environmental</strong> pollution is one of the biggest concerns.' },
        { infinitive: 'Pollution', translation: 'загрязнение', example: '<strong>Pollution</strong> is one of the biggest concerns facing the world.' },
        { infinitive: 'Concern', translation: 'проблема, тревога', example: 'Water pollution is of major <strong>concern</strong>.' },
        { infinitive: 'Harmful', translation: 'вредный', example: 'The presence of <strong>harmful</strong> substances.' },
        { infinitive: 'Substances', translation: 'вещества', example: 'Harmful <strong>substances</strong> and materials.' },
        { infinitive: 'Materials', translation: 'материалы', example: 'Harmful substances and <strong>materials</strong> in the environment.' },
        { infinitive: 'Ecosystems', translation: 'экосистемы', example: 'Cause severe damage to <strong>ecosystems</strong>.' },
        { infinitive: 'Health', translation: 'здоровье', example: 'The <strong>health</strong> of living organisms.' },
        { infinitive: 'Organisms', translation: 'организмы', example: 'The health of living <strong>organisms</strong>.' },
        { infinitive: 'Air', translation: 'воздух', example: '<strong>Air</strong> pollution is one form of environmental pollution.' },
        { infinitive: 'Release', translation: 'выброс', example: 'Caused by the <strong>release</strong> of harmful gases.' },
        { infinitive: 'Gases', translation: 'газы', example: 'Release of harmful <strong>gases</strong> and particles.' },
        { infinitive: 'Particles', translation: 'частицы', example: 'Harmful gases and <strong>particles</strong> into the atmosphere.' },
        { infinitive: 'Atmosphere', translation: 'атмосфера', example: 'Particles into the <strong>atmosphere</strong>.' },
        { infinitive: 'Combustion', translation: 'сгорание', example: '<strong>Combustion</strong> of fossil fuels.' },
        { infinitive: 'Fossil fuels', translation: 'ископаемое топливо', example: 'Combustion of <strong>fossil fuels</strong>.' },
        { infinitive: 'Industrial', translation: 'промышленный', example: '<strong>Industrial</strong> processes and transportation.' },
        { infinitive: 'Transportation', translation: 'транспорт', example: 'Industrial processes and <strong>transportation</strong>.' },
        { infinitive: 'Impact', translation: 'воздействие', example: 'Have a serious <strong>impact</strong> on the quality of air.' },
        { infinitive: 'Respiratory', translation: 'дыхательный', example: '<strong>Respiratory</strong> problems and cardiovascular diseases.' },
        { infinitive: 'Cardiovascular', translation: 'сердечно-сосудистый', example: '<strong>Cardiovascular</strong> diseases and cancer.' },
        { infinitive: 'Diseases', translation: 'заболевания', example: 'Cardiovascular <strong>diseases</strong> and cancer.' },
        { infinitive: 'Water', translation: 'вода', example: '<strong>Water</strong> pollution is of major concern.' },
        { infinitive: 'Toxic', translation: 'токсичный', example: 'Release of <strong>toxic</strong> chemicals.' },
        { infinitive: 'Chemicals', translation: 'химикаты', example: 'Release of toxic <strong>chemicals</strong>.' },
        { infinitive: 'Waste', translation: 'отходы', example: 'Industrial <strong>waste</strong> and other pollutants.' },
        { infinitive: 'Contamination', translation: 'загрязнение', example: '<strong>Contamination</strong> of drinking water.' },
        { infinitive: 'Biodiversity', translation: 'биоразнообразие', example: 'Loss of aquatic <strong>biodiversity</strong>.' },
        { infinitive: 'Soil', translation: 'почва', example: '<strong>Soil</strong> pollution is another issue.' },
        { infinitive: 'Fertility', translation: 'плодородие', example: 'Impact on soil <strong>fertility</strong>.' },
        { infinitive: 'Pesticides', translation: 'пестициды', example: 'Chemical fertilizers and <strong>pesticides</strong>.' },
        { infinitive: 'Vegetation', translation: 'растительность', example: 'Damage crops and <strong>vegetation</strong>.' },
        { infinitive: 'Noise', translation: 'шум', example: '<strong>Noise</strong> pollution is often overlooked.' },
        { infinitive: 'Excessive', translation: 'чрезмерный', example: '<strong>Excessive</strong> noise levels from traffic.' },
        { infinitive: 'Disturbances', translation: 'нарушения', example: 'Hearing loss and sleep <strong>disturbances</strong>.' },
        { infinitive: 'Consequences', translation: 'последствия', example: 'The <strong>consequences</strong> of environmental pollution.' },
        { infinitive: 'Climate change', translation: 'изменение климата', example: 'Loss of biodiversity and <strong>climate change</strong>.' },
        { infinitive: 'Governments', translation: 'правительства', example: '<strong>Governments</strong> must take action.' },
        { infinitive: 'Businesses', translation: 'бизнес-структуры', example: '<strong>Businesses</strong> must take responsibility.' },
        { infinitive: 'Regulate', translation: 'регулировать', example: '<strong>Regulate</strong> and monitor emissions.' },
        { infinitive: 'Monitor', translation: 'контролировать', example: 'Regulate and <strong>monitor</strong> emissions.' },
        { infinitive: 'Responsibility', translation: 'ответственность', example: 'Take <strong>responsibility</strong> for their environmental impact.' },
        { infinitive: 'Reduce', translation: 'уменьшать', example: 'Take steps to <strong>reduce</strong> pollution.' },
        { infinitive: 'Recycling', translation: 'переработка', example: 'Using public transport and <strong>recycling</strong>.' },
        { infinitive: 'Energy', translation: 'энергия', example: 'Reducing their <strong>energy</strong> consumption.' },
        { infinitive: 'Consumption', translation: 'потребление', example: 'Reduce their energy <strong>consumption</strong>.' },
        { infinitive: 'Sustainable', translation: 'устойчивый', example: 'A cleaner and more <strong>sustainable</strong> future.' },
        { infinitive: 'Challenge', translation: 'вызов', example: 'A significant <strong>challenge</strong> facing our planet.' },
        { infinitive: 'Generations', translation: 'поколения', example: 'Future for <strong>generations</strong> to come.' },
        { infinitive: 'Future', translation: 'будущее', example: 'A sustainable <strong>future</strong> for generations to come.' }
    ]
};
